services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: botscan
      POSTGRES_PASSWORD: botscan_pass
      POSTGRES_DB: botscan_db
    ports:
      - '5432:5432'
    volumes:
      - ./backend/prisma/migrations/20260211202629_init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://botscan:botscan_pass@postgres:5432/botscan_db
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules

  bot:
    image: bot-scan:latest
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/src:/app/src
          
    ports:
      - "3003:3003"

  scraper:
    image: scraper-scan:latest
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
    ports:
      - "3004:3000"

volumes:
  postgres_data:
