FROM node:24-slim

WORKDIR /app

COPY package*.json ./
COPY config ./
COPY prisma ./prisma

RUN apt-get update \
    && apt-get install -y libssl-dev openssl \
    && npm install \
    # && npm run db:migrate \
    && npm run db:generate

# COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
