FROM node:22-slim

WORKDIR /app

COPY package*.json ./
COPY config ./

RUN apt-get update \
    && apt-get install -y libssl-dev openssl \
    && npm install 
    # && prisma generate

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
